# -*- coding: utf-8 -*-
"""KNN MODEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHfcvsC2FlMhAIGKE-9pOjfA4RIFmLPT
"""

#Libraries needed for task
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

"""LOAD DATASET AND CHECK DATA CHARACTERISTICS"""

df = pd.read_csv('/content/plant_growth_data.csv') #Load dataset

df.head()#Display first five rows of the dataset

df.describe()#Display statistical summary of the dataset

#Check for missing values
df.isnull().sum()

df.shape#Check for the number of rows and columns

df.dtypes#Check for data types

# Perform one-hot encoding on categorical features
categorical_cols = ['Soil_Type', 'Water_Frequency', 'Fertilizer_Type']#Define a list of column names that contain categorical data to be encoded
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)#Create a new DataFrame with one-hot encoding applied to the specified categorical columns, converting them into binary columns for each category, and drop the first category to avoid multicollinearity

# Display the first few rows of the encoded DataFrame
display(df_encoded.head())

df_encoded.shape #Return a tuple representing the dimensions of the DataFrame df_encoded, where the first element is the number of rows and the second is the number of columns

#Splitting the encoded data into X and y, and then into training and testing sets
X = df_encoded.drop('Growth_Milestone', axis=1)#Create a new DataFrame X by removing the 'Growth_Milestone' column from df_encoded, where axis=1 specifies that the operation is performed on columns
y = df_encoded['Growth_Milestone']# Assign the 'Growth_Milestone' column from the encoded DataFrame to the variable y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)#Split the feature data (X) and target variable (y) into training and testing sets, with 20% of the data allocated for testing and a fixed random seed for reproducibility

scaler = MinMaxScaler(feature_range=(0, 1))#Initialize a MinMaxScaler object to scale features to a range between 0 and 1
X_train_scaled = scaler.fit_transform(X_train)#Fit the MinMaxScaler to the training data and transform it to scale features to the range [0, 1]
X_test_scaled = scaler.transform(X_test)# Transform the test data using the fitted MinMaxScaler to scale features to the range [0, 1]
knn = KNeighborsClassifier(n_neighbors=3)#Initialize a K-Nearest Neighbors classifier with 3 neighbors

knn.fit(X_train_scaled, y_train)# Train the K-Nearest Neighbors classifier using the scaled training features and corresponding target labels

y_pred = knn.predict(X_test_scaled)# Generate predictions for the test data using the trained K-Nearest Neighbors classifier
print(y_pred)# Print the predicted target labels for the test data

knn.score(X_test_scaled, y_test)# Compute and return the accuracy score of the K-Nearest Neighbors classifier on the scaled test data

cm = confusion_matrix(y_test, y_pred)# Generate a confusion matrix to evaluate the performance of the K-Nearest Neighbors classifier by comparing the true test labels (y_test) with the predicted labels (y_pred)
print(cm)#Display the results.

sns.heatmap(cm, annot=True, cmap='summer')#show Confusion Matrix as heatmap
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

cr = classification_report(y_test, y_pred)# Generate a classification report containing precision, recall, F1-score, and support for each class by comparing the true test labels (y_test) with the predicted labels (y_pred)
print(cr)#Display results